module.exports = {
  'secret': 'supersecret',
  'accessKeyId': 'AKIASYCFHD36G5CA3NXV',
  'secretAccessKey': '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',
  'region': 'us-west-2',
  "url":"http://103.1.114.100/",
  //"url":"http://192.168.1.17/",
  //"GoogleAPIKey":"AIzaSyA9g4693wrgrTyhWmyJzb3RGXFV6f1Z1og",
  "GoogleAPIKey":"AIzaSyBxcLuGJ9njsklG_5xukjFb8F5G6BugM_w",
  "AWShost": 'asoqa2zjmpz13.iot.ap-south-1.amazonaws.com',
  "FIREBASE_SERVER_KEY":"AAAADT756Wk:APA91bE0Lq106AI_JKB-lohwwklNqq7Wt4DCaRPIl3Hh_MTbwN5d38CmHouWioGWI5rDXrzDeg_5G_Ilq1Plcr9gFp2JAsEJCgwqRrGqE23cA7bUDXt80DSGEBmYMDdpvwB_tBmmaiv3",
  "BitMessages": {
    "SuperAdminAlarm1Arr": [
      { "message": "Battery 1 Voltage High Alarm", "nomenclature": "Bat1-HiVolt", "detail": "alarm" },
      { "message": "Battery 1 Voltage Lower Alarm", "nomenclature": "Bat1-LoVolt", "detail": "alarm" },
      { "message": "Battery 1 Over Charge Alarm", "nomenclature": "Bat1-OvrChg", "detail": "alarm" },
      { "message": "Battery1 OverLoad Cut Alarm", "nomenclature": "Bat1-OvrLoad", "detail": "alarm" },
      { "message": "Battery 1 Over Charge Temperature Alarm", "nomenclature": "Bat1-ChgOvrTemp", "detail": "alarm" },
      { "message": "Battery 1 Over Discharge Temperature Alarm", "nomenclature": "Bat1-DischgOvrTemp", "detail": "alarm" },
      { "message": "Battery 1 Low SOC Alarm", "nomenclature": "Bat1-LoSOC", "detail": "alarm" },
      { "message": "Battery 1 Low SOH Alarm", "nomenclature": "Bat1-LoSOH", "detail": "alarm" },
      { "message": "Battery 1 Voltage High Cut Warning", "nomenclature": "Bat1-HiVolt", "detail": "warning" },
      { "message": "Battery 1 Voltage Lower Cut Warning", "nomenclature": "Bat1-LoVolt", "detail": "warning" },
      { "message": "Battery 1 Over Charge Warning", "nomenclature": "Bat1-OvrChg", "detail": "warning" },
      { "message": "Battery 1 OverLoad Warning", "nomenclature": "Bat1-OvrLoad", "detail": "warning" },
      { "message": "Battery 1 Over Charge Temperature Warning", "nomenclature": "Bat1-ChgOvrTemp", "detail": "warning" },
      { "message": "Battery 1 Over Discharge Temperature Warning", "nomenclature": "Bat1-DischgOvrTemp", "detail": "warning" },
      { "message": "Battery 1 Low SOC Warning", "nomenclature": "Bat1-LoSOC", "detail": "warning" },
      { "message": "Battery 1 Low SOH Warning", "nomenclature": "Bat1-LoSOH", "detail": "warning" }
    ],
    "SuperAdminAlarm2Arr": [
      { "message": "Battery 2 Voltage High Alarm", "nomenclature": "Bat2-HiVolt", "detail": "alarm" },
      { "message": "Battery 2 Voltage Lower Alarm", "nomenclature": "Bat2-LoVolt", "detail": "alarm" },
      { "message": "Battery 2 Over Charge Alarm", "nomenclature": "Bat2-OvrChg", "detail": "alarm" },
      { "message": "Battery2 OverLoad Cut Alarm", "nomenclature": "Bat2-OvrLoad", "detail": "alarm" },
      { "message": "Battery 2 Over Charge Temperature Alarm", "nomenclature": "Bat2-ChgOvrTemp", "detail": "alarm" },
      { "message": "Battery 2 Over Discharge Temperature Alarm", "nomenclature": "Bat2-DischgOvrTemp", "detail": "alarm" },
      { "message": "Battery 2 Low SOC Alarm", "nomenclature": "Bat2-LoSOC", "detail": "alarm" },
      { "message": "Battery 2 Low SOH Alarm", "nomenclature": "Bat2-LoSOH", "detail": "alarm" },
      { "message": "Battery 2 Voltage High Cut Warning", "nomenclature": "Bat2-HiVolt", "detail": "warning" },
      { "message": "Battery 2 Voltage Lower Cut Warning", "nomenclature": "Bat2-LoVolt", "detail": "warning" },
      { "message": "Battery 2 Over Charge Warning", "nomenclature": "Bat2-OvrChg", "detail": "warning" },
      { "message": "Battery 2 OverLoad Warning", "nomenclature": "Bat2-OvrLoad", "detail": "warning" },
      { "message": "Battery 2 Over Charge Temperature Warning", "nomenclature": "Bat2-ChgOvrTemp", "detail": "warning" },
      { "message": "Battery 2 Over Discharge Temperature Warning", "nomenclature": "Bat2-DischgOvrTemp", "detail": "warning" },
      { "message": "Battery 2 Low SOC Warning", "nomenclature": "Bat2-LoSOC", "detail": "warning" },
      { "message": "Battery 2 Low SOH Warning", "nomenclature": "Bat2-LoSOH", "detail": "warning" }
    ],
    "SuperAdminAlarm3Arr": [
      { "message": "Battery 3 Voltage High Alarm", "nomenclature": "Bat3-HiVolt", "detail": "alarm" },
      { "message": "Battery 3 Voltage Lower Alarm", "nomenclature": "Bat3-LoVolt", "detail": "alarm" },
      { "message": "Battery 3 Over Charge Alarm", "nomenclature": "Bat3-OvrChg", "detail": "alarm" },
      { "message": "Battery3 OverLoad Cut Alarm", "nomenclature": "Bat3-OvrLoad", "detail": "alarm" },
      { "message": "Battery 3 Over Charge Temperature Alarm", "nomenclature": "Bat3-ChgOvrTemp", "detail": "alarm" },
      { "message": "Battery 3 Over Discharge Temperature Alarm", "nomenclature": "Bat3-DischgOvrTemp", "detail": "alarm" },
      { "message": "Battery 3 Low SOC Alarm", "nomenclature": "Bat3-LoSOC", "detail": "alarm" },
      { "message": "Battery 3 Low SOH Alarm", "nomenclature": "Bat3-LoSOH", "detail": "alarm" },
      { "message": "Battery 3 Voltage High Cut Warning", "nomenclature": "Bat3-HiVolt", "detail": "warning" },
      { "message": "Battery 3 Voltage Lower Cut Warning", "nomenclature": "Bat3-LoVolt", "detail": "warning" },
      { "message": "Battery 3 Over Charge Warning", "nomenclature": "Bat3-OvrChg", "detail": "warning" },
      { "message": "Battery 3 OverLoad Warning", "nomenclature": "Bat3-OvrLoad", "detail": "warning" },
      { "message": "Battery 3 Over Charge Temperature Warning", "nomenclature": "Bat3-ChgOvrTemp", "detail": "warning" },
      { "message": "Battery 3 Over Discharge Temperature Warning", "nomenclature": "Bat3-DischgOvrTemp", "detail": "warning" },
      { "message": "Battery 3 Low SOC Warning", "nomenclature": "Bat3-LoSOC", "detail": "warning" },
      { "message": "Battery 3 Low SOH Warning", "nomenclature": "Bat3-LoSOH", "detail": "warning" }
    ],
    "SuperAdminAlarm4Arr": [
      { "message": "Battery 1-3  Low Cycle Count Warning Battery 1", "nomenclature": "Bat1-LoCycleCnt", "detail": "" },
      { "message": "Battery 1-3  Low Cycle Count Alarm Battery1", "nomenclature": "Bat1-LoCycleCnt", "detail": "" },
      { "message": "Battery 1-3  Charge Mosfet Status Battery 1", "nomenclature": "", "detail": "" },
      { "message": "Battery 1-3  Discharge Mosfet Status Battery 1", "nomenclature": "", "detail": "" },
      { "message": "Battery 1-3  Hardware Fault Batt1", "nomenclature": "Bat1-HWFail", "detail": "" },
      { "message": "Battery 1-3  Low Cycle Count Warning Battery 2", "nomenclature": "Bat2-LoCycleCnt", "detail": "" },
      { "message": "Battery 1-3  Low Cycle Count Alarm Battery2", "nomenclature": "", "detail": "" },
      { "message": "Battery 1-3  Charge Mosfet Status Battery 2", "nomenclature": "", "detail": "" },
      { "message": "Battery 1-3  Discharge Mosfet Status Battery 2", "nomenclature": "", "detail": "" },
      { "message": "Battery 1-3  Hardware Fault Batt2", "nomenclature": "Bat2-HWFail", "detail": "" },
      { "message": "Battery 1-3  Low Cycle Count Warning Battery 3", "nomenclature": "Bat3-LoCycleCnt", "detail": "" },
      { "message": "Battery 1-3  Low Cycle Count Alarm Battery3", "nomenclature": "", "detail": "" },
      { "message": "Battery 1-3  Charge Mosfet Status Battery 3", "nomenclature": "", "detail": "" },
      { "message": "Battery 1-3  Discharge Mosfet Status Battery 3", "nomenclature": "", "detail": "" },
      { "message": "Battery 1-3  Hardware Fault Batt3", "nomenclature": "Bat3-HWFail", "detail": "" },
      { "message": "Battery 1-3  Reserve", "nomenclature": "", "detail": "" }
    ],
    "SuperAdminStatus1Arr": [
      { "message": "Status 1 Communication Fail Batt1", "nomenclature": "Bat1-LoCycleCnt", "detail": "" },
      { "message": "Status 1 Communication Fail Batt2", "nomenclature": "Bat1-LoCycleCnt", "detail": "" },
      { "message": "Status 1 Communication Fail Batt3", "nomenclature": "", "detail": "" },
      { "message": "Status 1 (SOC > 50) LED 1", "nomenclature": "", "detail": "" },
      { "message": "Status 1 (50 >= SOC >= 30) LED 2", "nomenclature": "Bat1-HWFail", "detail": "" },
      { "message": "Status 1 (30 > SOC) LED 3", "nomenclature": "Bat2-LoCycleCnt", "detail": "" },
      { "message": "Status 1 GPS Antenna Tempered", "nomenclature": "", "detail": "" },
      { "message": "Status 1 GPS Low Statelite Detect", "nomenclature": "", "detail": "" },
      { "message": "Status 1 Battery Charging/Discharging", "nomenclature": "", "detail": "" },
      { "message": "Status 1 Battery Full Charged", "nomenclature": "Bat2-HWFail", "detail": "" },
      { "message": "Status 1 Charge Mosfet Status", "nomenclature": "Bat3-LoCycleCnt", "detail": "" },
      { "message": "Status 1 Discharge Mosfet Status", "nomenclature": "", "detail": "" },
      { "message": "Status 1 Telematics Memory Error", "nomenclature": "", "detail": "" },
      { "message": "Status 1 Telematics Charge Mosfet Short", "nomenclature": "", "detail": "" },
      { "message": "Status 1 Telematics Discharge Mosfet Short", "nomenclature": "Bat3-HWFail", "detail": "" },
      { "message": "Status 1 Telematics Charge Mosfet Open", "nomenclature": "", "detail": "" }
    ],
    "SuperAdminStatus2Arr": [
      { "message": "Status 2 Telematics Discharge Mosfet Open", "nomenclature": "", "detail": "" },
      { "message": "Status 2 Reserve", "nomenclature": "", "detail": "" },
      { "message": "Status 2 Reserve", "nomenclature": "", "detail": "" },
      { "message": "Status 2 Reserve", "nomenclature": "", "detail": "" },
      { "message": "Status 2 Reserve", "nomenclature": "", "detail": "" },
      { "message": "Status 2 Reserve", "nomenclature": "", "detail": "" },
      { "message": "Status 2 Reserve", "nomenclature": "", "detail": "" },
      { "message": "Status 2 Reserve", "nomenclature": "", "detail": "" },
      { "message": "Status 2 Reserve", "nomenclature": "", "detail": "" },
      { "message": "Status 2 Reserve", "nomenclature": "", "detail": "" },
      { "message": "Status 2 Reserve", "nomenclature": "", "detail": "" },
      { "message": "Status 2 Reserve", "nomenclature": "", "detail": "" },
      { "message": "Status 2 Reserve", "nomenclature": "", "detail": "" },
      { "message": "Status 2 Reserve", "nomenclature": "", "detail": "" },
      { "message": "Status 2 Reserve", "nomenclature": "", "detail": "" },
      { "message": "Status 2 Reserve", "nomenclature": "", "detail": "" }
    ],

    "FleetManagerAlarm1Arr": [
      { "message": "Reinitialise Charging", "Nomenclature": "Bat1-HiVolt", "detail": "alarm" },
      { "message": "Start Charging", "Nomenclature": "Bat1-LoVolt", "detail": "alarm" },
      { "message": "Reinitialise Charging", "Nomenclature": "Bat1-OvrChg", "detail": "alarm" },
      { "message": "Stop Vehicle", "Nomenclature": "Bat1-OvrLoad", "detail": "alarm" },
      { "message": "Wait for Normal Temp", "Nomenclature": "Bat1-ChgOvrTemp", "detail": "alarm" },
      { "message": "Wait for Normal Temp", "Nomenclature": "Bat1-DischgOvrTemp", "detail": "alarm" },
      { "message": "Start Charging", "Nomenclature": "Bat1-LoSOC", "detail": "alarm" },
      { "message": "Change Battery", "Nomenclature": "Bat1-LoSOH", "detail": "alarm" },
      { "message": "Stop Charging", "Nomenclature": "Bat1-HiVolt", "detail": "warning" },
      { "message": "Start Charging", "Nomenclature": "Bat1-LoVolt", "detail": "warning" },
      { "message": "Stop Charging", "Nomenclature": "Bat1-OvrChg", "detail": "warning" },
      { "message": "Stop Vehicle", "Nomenclature": "Bat1-OvrLoad", "detail": "warning" },
      { "message": "Stop Charging", "Nomenclature": "Bat1-ChgOvrTemp", "detail": "warning" },
      { "message": "Stop Vehicle ", "Nomenclature": "Bat1-DischgOvrTemp", "detail": "warning" },
      { "message": "Start Charging", "Nomenclature": "Bat1-LoSOC", "detail": "warning" },
      { "message": "", "Nomenclature": "", "detail": "warning" }
    ],
    "FleetManagerAlarm2Arr": [
      { "message": "Reinitialise Charging", "Nomenclature": "Bat2-HiVolt", "detail": "alarm" },
      { "message": "Start Charging", "Nomenclature": "Bat2-LoVolt", "detail": "alarm" },
      { "message": "Reinitialise Charging", "Nomenclature": "Bat2-OvrChg", "detail": "alarm" },
      { "message": "Stop Vehicle", "Nomenclature": "Bat2-OvrLoad", "detail": "alarm" },
      { "message": "Wait for Normal Temp", "Nomenclature": "Bat2-ChgOvrTemp", "detail": "alarm" },
      { "message": "Wait for Normal Temp", "Nomenclature": "Bat2-DischgOvrTemp", "detail": "alarm" },
      { "message": "Start Charging", "Nomenclature": "Bat2-LoSOC", "detail": "alarm" },
      { "message": "Change Battery", "Nomenclature": "Bat2-LoSOH", "detail": "alarm" },
      { "message": "Stop Charging", "Nomenclature": "Bat2-HiVolt", "detail": "warning" },
      { "message": "Start Charging", "Nomenclature": "Bat2-LoVolt", "detail": "warning" },
      { "message": "Stop Charging", "Nomenclature": "Bat2-OvrChg", "detail": "warning" },
      { "message": "Stop Vehicle", "Nomenclature": "Bat2-OvrLoad", "detail": "warning" },
      { "message": "Stop Charging", "Nomenclature": "Bat2-ChgOvrTemp", "detail": "warning" },
      { "message": "Stop Vehicle ", "Nomenclature": "Bat2-DischgOvrTemp", "detail": "warning" },
      { "message": "Start Charging", "Nomenclature": "Bat2-LoSOC", "detail": "warning" },
      { "message": "", "Nomenclature": "", "detail": "warning" }
    ],
    "FleetManagerAlarm3Arr": [
      { "message": "Reinitialise Charging", "Nomenclature": "Bat3-HiVolt", "detail": "alarm" },
      { "message": "Start Charging", "Nomenclature": "Bat3-LoVolt", "detail": "alarm" },
      { "message": "Reinitialise Charging", "Nomenclature": "Bat3-OvrChg", "detail": "alarm" },
      { "message": "Stop Vehicle", "Nomenclature": "Bat3-OvrLoad", "detail": "alarm" },
      { "message": "Wait for Normal Temp", "Nomenclature": "Bat3-ChgOvrTemp", "detail": "alarm" },
      { "message": "Wait for Normal Temp", "Nomenclature": "Bat3-DischgOvrTemp", "detail": "alarm" },
      { "message": "Start Charging", "Nomenclature": "Bat3-LoSOC", "detail": "alarm" },
      { "message": "Change Battery", "Nomenclature": "Bat3-LoSOH", "detail": "alarm" },
      { "message": "Stop Charging", "Nomenclature": "Bat3-HiVolt", "detail": "warning" },
      { "message": "Start Charging", "Nomenclature": "Bat3-LoVolt", "detail": "warning" },
      { "message": "Stop Charging", "Nomenclature": "Bat3-OvrChg", "detail": "warning" },
      { "message": "Stop Vehicle", "Nomenclature": "Bat3-OvrLoad", "detail": "warning" },
      { "message": "Stop Charging", "Nomenclature": "Bat3-ChgOvrTemp", "detail": "warning" },
      { "message": "Stop Vehicle ", "Nomenclature": "Bat3-DischgOvrTemp", "detail": "warning" },
      { "message": "Start Charging", "Nomenclature": "Bat3-LoSOC", "detail": "warning" },
      { "message": "", "Nomenclature": "", "detail": "warning" }
    ],
    "FleetManagerAlarm4Arr": [
      { "message": "Change Battery1", "nomenclature": "Bat1-LoCycleCnt", "detail": "" },
      { "message": "Change Battery1", "nomenclature": "Bat1-LoCycleCnt", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "Change Battery1", "nomenclature": "Bat1-HWFail", "detail": "" },
      { "message": "Change Battery2", "nomenclature": "Bat2-LoCycleCnt", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "Change Battery2", "nomenclature": "Bat2-HWFail", "detail": "" },
      { "message": "BatChange Battery3", "nomenclature": "Bat3-LoCycleCnt", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "Change Battery3", "nomenclature": "Bat3-HWFail", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" }
    ],

    "SystemIntegraterAlarm1Arr": [
      { "message": "Reinitialise Charging", "Nomenclature": "Bat1-HiVolt", "detail": "alarm" },
      { "message": "Start Charging", "Nomenclature": "Bat1-LoVolt", "detail": "alarm" },
      { "message": "Reinitialise Charging", "Nomenclature": "Bat1-OvrChg", "detail": "alarm" },
      { "message": "Stop Vehicle", "Nomenclature": "Bat1-OvrLoad", "detail": "alarm" },
      { "message": "Wait for Normal Temp", "Nomenclature": "Bat1-ChgOvrTemp", "detail": "alarm" },
      { "message": "Wait for Normal Temp", "Nomenclature": "Bat1-DischgOvrTemp", "detail": "alarm" },
      { "message": "Start Charging", "Nomenclature": "Bat1-LoSOC", "detail": "alarm" },
      { "message": "Change Battery", "Nomenclature": "Bat1-LoSOH", "detail": "alarm" },
      { "message": "Stop Charging", "Nomenclature": "Bat1-HiVolt", "detail": "warning" },
      { "message": "Start Charging", "Nomenclature": "Bat1-LoVolt", "detail": "warning" },
      { "message": "Stop Charging", "Nomenclature": "Bat1-OvrChg", "detail": "warning" },
      { "message": "Stop Vehicle", "Nomenclature": "Bat1-OvrLoad", "detail": "warning" },
      { "message": "Stop Charging", "Nomenclature": "Bat1-ChgOvrTemp", "detail": "warning" },
      { "message": "Stop Vehicle ", "Nomenclature": "Bat1-DischgOvrTemp", "detail": "warning" },
      { "message": "Start Charging", "Nomenclature": "Bat1-LoSOC", "detail": "warning" },
      { "message": "", "Nomenclature": "", "detail": "warning" }
    ],
    "SystemIntegraterAlarm2Arr": [
      { "message": "Reinitialise Charging", "Nomenclature": "Bat2-HiVolt", "detail": "alarm" },
      { "message": "Start Charging", "Nomenclature": "Bat2-LoVolt", "detail": "alarm" },
      { "message": "Reinitialise Charging", "Nomenclature": "Bat2-OvrChg", "detail": "alarm" },
      { "message": "Stop Vehicle", "Nomenclature": "Bat2-OvrLoad", "detail": "alarm" },
      { "message": "Wait for Normal Temp", "Nomenclature": "Bat2-ChgOvrTemp", "detail": "alarm" },
      { "message": "Wait for Normal Temp", "Nomenclature": "Bat2-DischgOvrTemp", "detail": "alarm" },
      { "message": "Start Charging", "Nomenclature": "Bat2-LoSOC", "detail": "alarm" },
      { "message": "Change Battery", "Nomenclature": "Bat2-LoSOH", "detail": "alarm" },
      { "message": "Stop Charging", "Nomenclature": "Bat2-HiVolt", "detail": "warning" },
      { "message": "Start Charging", "Nomenclature": "Bat2-LoVolt", "detail": "warning" },
      { "message": "Stop Charging", "Nomenclature": "Bat2-OvrChg", "detail": "warning" },
      { "message": "Stop Vehicle", "Nomenclature": "Bat2-OvrLoad", "detail": "warning" },
      { "message": "Stop Charging", "Nomenclature": "Bat2-ChgOvrTemp", "detail": "warning" },
      { "message": "Stop Vehicle ", "Nomenclature": "Bat2-DischgOvrTemp", "detail": "warning" },
      { "message": "Start Charging", "Nomenclature": "Bat2-LoSOC", "detail": "warning" },
      { "message": "", "Nomenclature": "", "detail": "warning" }
    ],
    "SystemIntegraterAlarm3Arr": [
      { "message": "Reinitialise Charging", "Nomenclature": "Bat3-HiVolt", "detail": "alarm" },
      { "message": "Start Charging", "Nomenclature": "Bat3-LoVolt", "detail": "alarm" },
      { "message": "Reinitialise Charging", "Nomenclature": "Bat3-OvrChg", "detail": "alarm" },
      { "message": "Stop Vehicle", "Nomenclature": "Bat3-OvrLoad", "detail": "alarm" },
      { "message": "Wait for Normal Temp", "Nomenclature": "Bat3-ChgOvrTemp", "detail": "alarm" },
      { "message": "Wait for Normal Temp", "Nomenclature": "Bat3-DischgOvrTemp", "detail": "alarm" },
      { "message": "Start Charging", "Nomenclature": "Bat3-LoSOC", "detail": "alarm" },
      { "message": "Change Battery", "Nomenclature": "Bat3-LoSOH", "detail": "alarm" },
      { "message": "Stop Charging", "Nomenclature": "Bat3-HiVolt", "detail": "warning" },
      { "message": "Start Charging", "Nomenclature": "Bat3-LoVolt", "detail": "warning" },
      { "message": "Stop Charging", "Nomenclature": "Bat3-OvrChg", "detail": "warning" },
      { "message": "Stop Vehicle", "Nomenclature": "Bat3-OvrLoad", "detail": "warning" },
      { "message": "Stop Charging", "Nomenclature": "Bat3-ChgOvrTemp", "detail": "warning" },
      { "message": "Stop Vehicle ", "Nomenclature": "Bat3-DischgOvrTemp", "detail": "warning" },
      { "message": "Start Charging", "Nomenclature": "Bat3-LoSOC", "detail": "warning" },
      { "message": "", "Nomenclature": "", "detail": "warning" }
    ],
    "SystemIntegraterAlarm4Arr": [
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "Change Battery1", "nomenclature": "Bat1-HWFail", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "Change Battery2", "nomenclature": "Bat2-HWFail", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "Change Battery3", "nomenclature": "Bat3-HWFail", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" }
    ],

    "BatteryManufacturerAlarm1Arr": [
      { "message": "Battery1 Voltage High Cut Alarm", "nomenclature": "Bat1-HiVolt", "detail": "alarm" },
      { "message": "Battery1 Voltage Lower Cut Alarm", "nomenclature": "Bat1-LoVolt", "detail": "alarm" },
      { "message": "Battery1 Over Charge Cut Alarm", "nomenclature": "Bat1-OvrChg", "detail": "alarm" },
      { "message": "Battery1 OverLoad Cut Alarm", "nomenclature": "Bat1-OvrLoad", "detail": "alarm" },
      { "message": "Battery1 Over Charge Temperature Cut Alarm", "nomenclature": "Bat1-ChgOvrTemp", "detail": "alarm" },
      { "message": "Battery1 Over Discharge Temperature Cut Alarm", "nomenclature": "Bat1-DischgOvrTemp", "detail": "alarm" },
      { "message": "Battery1 Low SOC Cut Alarm", "nomenclature": "Bat1-LoSOC", "detail": "alarm" },
      { "message": "Battery1 Low SOH Cut Alarm", "nomenclature": "Bat1-LoSOH", "detail": "alarm" },
      { "message": "Battery1 Voltage High Cut Warning", "nomenclature": "Bat1-HiVolt", "detail": "warning" },
      { "message": "Battery1 Voltage Lower Cut Warning", "nomenclature": "Bat1-LoVolt", "detail": "warning" },
      { "message": "Battery1 Over Charge Cut Warning", "nomenclature": "Bat1-OvrChg", "detail": "warning" },
      { "message": "Battery1 OverLoad Cut Warning", "nomenclature": "Bat1-OvrLoad", "detail": "warning" },
      { "message": "Battery1 Over Charge Temperature Cut Warning", "nomenclature": "Bat1-ChgOvrTemp", "detail": "warning" },
      { "message": "Battery1 Over Discharge Temperature Cut Warning", "nomenclature": "Bat1-DischgOvrTemp", "detail": "warning" },
      { "message": "Battery1 Low SOC Cut Warning", "nomenclature": "Bat1-LoSOC", "detail": "warning" },
      { "message": "Battery1 Low SOH Cut Warning", "nomenclature": "Bat1-LoSOH", "detail": "warning" }
    ],
    "BatteryManufacturerAlarm2Arr": [
      { "message": "Battery2 Voltage High Cut Alarm", "nomenclature": "Bat2-HiVolt", "detail": "alarm" },
      { "message": "Battery2 Voltage Lower Cut Alarm", "nomenclature": "Bat2-LoVolt", "detail": "alarm" },
      { "message": "Battery2 Over Charge Cut Alarm", "nomenclature": "Bat2-OvrChg", "detail": "alarm" },
      { "message": "Battery2 OverLoad Cut Alarm", "nomenclature": "Bat2-OvrLoad", "detail": "alarm" },
      { "message": "Battery2 Over Charge Temperature Cut Alarm", "nomenclature": "Bat2-ChgOvrTemp", "detail": "alarm" },
      { "message": "Battery2 Over Discharge Temperature Cut Alarm", "nomenclature": "Bat2-DischgOvrTemp", "detail": "alarm" },
      { "message": "Battery2 Low SOC Cut Alarm", "nomenclature": "Bat2-LoSOC", "detail": "alarm" },
      { "message": "Battery2 Low SOH Cut Alarm", "nomenclature": "Bat2-LoSOH", "detail": "alarm" },
      { "message": "Battery2 Voltage High Cut Warning", "nomenclature": "Bat2-HiVolt", "detail": "warning" },
      { "message": "Battery2 Voltage Lower Cut Warning", "nomenclature": "Bat2-LoVolt", "detail": "warning" },
      { "message": "Battery2 Over Charge Cut Warning", "nomenclature": "Bat2-OvrChg", "detail": "warning" },
      { "message": "Battery2 OverLoad Cut Warning", "nomenclature": "Bat2-OvrLoad", "detail": "warning" },
      { "message": "Battery2 Over Charge Temperature Cut Warning", "nomenclature": "Bat2-ChgOvrTemp", "detail": "warning" },
      { "message": "Battery2 Over Discharge Temperature Cut Warning", "nomenclature": "Bat2-DischgOvrTemp", "detail": "warning" },
      { "message": "Battery2 Low SOC Cut Warning", "nomenclature": "Bat2-LoSOC", "detail": "warning" },
      { "message": "Battery2 Low SOH Cut Warning", "nomenclature": "Bat2-LoSOH", "detail": "warning" }
    ],
    "BatteryManufacturerAlarm3Arr": [
      { "message": "Battery3 Voltage High Cut Alarm", "nomenclature": "Bat3-HiVolt", "detail": "alarm" },
      { "message": "Battery3 Voltage Lower Cut Alarm", "nomenclature": "Bat3-LoVolt", "detail": "alarm" },
      { "message": "Battery3 Over Charge Cut Alarm", "nomenclature": "Bat3-OvrChg", "detail": "alarm" },
      { "message": "Battery3 OverLoad Cut Alarm", "nomenclature": "Bat3-OvrLoad", "detail": "alarm" },
      { "message": "Battery3 Over Charge Temperature Cut Alarm", "nomenclature": "Bat3-ChgOvrTemp", "detail": "alarm" },
      { "message": "Battery3 Over Discharge Temperature Cut Alarm", "nomenclature": "Bat3-DischgOvrTemp", "detail": "alarm" },
      { "message": "Battery3 Low SOC Cut Alarm", "nomenclature": "Bat3-LoSOC", "detail": "alarm" },
      { "message": "Battery3 Low SOH Cut Alarm", "nomenclature": "Bat3-LoSOH", "detail": "alarm" },
      { "message": "Battery3 Voltage High Cut Warning", "nomenclature": "Bat3-HiVolt", "detail": "warning" },
      { "message": "Battery3 Voltage Lower Cut Warning", "nomenclature": "Bat3-LoVolt", "detail": "warning" },
      { "message": "Battery3 Over Charge Cut Warning", "nomenclature": "Bat3-OvrChg", "detail": "warning" },
      { "message": "Battery3 OverLoad Cut Warning", "nomenclature": "Bat3-OvrLoad", "detail": "warning" },
      { "message": "Battery3 Over Charge Temperature Cut Warning", "nomenclature": "Bat3-ChgOvrTemp", "detail": "warning" },
      { "message": "Battery3 Over Discharge Temperature Cut Warning", "nomenclature": "Bat3-DischgOvrTemp", "detail": "warning" },
      { "message": "Battery3 Low SOC Cut Warning", "nomenclature": "Bat3-LoSOC", "detail": "warning" },
      { "message": "Battery3 Low SOH Cut Warning", "nomenclature": "Bat3-LoSOH", "detail": "warning" }
    ],
    "BatteryManufacturerAlarm4Arr": [
      { "message": "Change Battery1", "nomenclature": "Bat1-LoCycleCnt", "detail": "" },
      { "message": "Change Battery1", "nomenclature": "Bat1-LoCycleCnt", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "Change Battery1", "nomenclature": "Bat1-HWFail", "detail": "" },
      { "message": "Change Battery2", "nomenclature": "Bat2-LoCycleCnt", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "Change Battery2", "nomenclature": "Bat2-HWFail", "detail": "" },
      { "message": "BatChange Battery3", "nomenclature": "Bat3-LoCycleCnt", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" },
      { "message": "Change Battery3", "nomenclature": "Bat3-HWFail", "detail": "" },
      { "message": "", "nomenclature": "", "detail": "" }
    ]
  }
};